### ISSUE TITLE
Can't resolve 'path' when using linaria in layout.tsx

### ISSUE THREAD

**Issue by luizeboli** [dlehmhus/next-with-linaria#17]
Reproduction: https://github.com/luizeboli/next-with-linaria-bug

----

Node: 18.16.0
NPM: 9.5.1
MacOS: Big Sur

When running `npm run build` I'm receiving a lot of errors related to node apis like `Error: Can't resolve 'path' in '/test-linaria/node_modules/next/dist/server'` (contrived path)

Doing some investigation I realized these errors only happens when I use either `styled` or `css` function in the root `layout.tsx` file

**Comment by dlehmhus** [comment]
Hey @luizeboli, I think the issue here is that when linaria runs it tries to evaluate the import 
```ts
import { Metadata } from "next";
```
but that contains a lot of paths that only exist at build time. To fix that you have to change the import to 
```ts
import type { Metadata } from "next";
```
that way, linaria will not attempt to evaluate the import.

I definitely recommend to [configure eslint](https://typescript-eslint.io/rules/consistent-type-imports/) to do that for you!

**Comment by luizeboli** [comment]
Hi @dlehmhus!

Looks like this change solved the problem.

Thanks for your support :)
